IF OBJECT_ID('PRC_DATOS_EXTRAS_EMP')
	IS NOT NULL
DROP PROCEDURE PRC_DATOS_EXTRAS_EMP
GO

CREATE PROCEDURE PRC_DATOS_EXTRAS_EMP
(
	@pIdEmpleado	INT
)
AS

	SELECT IdEmpleado
		,NombreCompleto
		,FLOOR(DATEDIFF(DAY, FechaNacimiento, GETDATE())/365.25) EDAD
		,FLOOR(DATEDIFF(DAY, FechaIngreso, GETDATE())/365.25) ANTIGUEDAD_LABORAL
		,Foto
	FROM Empleado
	WHERE IdEmpleado = @pIdEmpleado