IF OBJECT_ID('PRC_LISTA_AREAS_X_ID')
	IS NOT NULL
DROP PROC PRC_LISTA_AREAS_X_ID

GO

CREATE PROCEDURE PRC_LISTA_AREAS_X_ID
(
	@pIdArea		INT	
)
AS

	SELECT IdArea
			,Nombre
			,Descripcion
	FROM AREA
	WHERE IdArea = @pIdArea